version: '3.4'
services:

  user-web-api:
    image: ${DOCKER_REGISTRY-}userwebapi
    container_name: user-web-api
    build:
      context: .
      dockerfile: ./backend/Dockerfile

  user-web-ui:
    image: ${DOCKER_REGISTRY-}usercontrolui
    container_name: user-web-ui
    build:
      context: .
      dockerfile: ./Dockerfile